### ISSUE TITLE
mixedmodels.jl

### ISSUE THREAD

**Issue by mkborregaard** [JuliaStats/StatsKit.jl#6]
On #4 I suggested MixedModels.jl, there seemed to be agreement, and @dmbates expressed his willingness to coordinate, but I think it was overlooked, so I'll just open this issue as a reminder.

**Comment by dmbates** [comment]
As stated, I am happy to coordinate.  I am in the process of updating the code for Julia v1.0.  I had a number of methods for generics like `Ac_mul_B!` that need rewriting for the new organization of the `LinearAlgebra` package.

Just let me know what you want me to do.

I am also willing to discuss moving the repository to a group like `JuliaStats`.  As I near my 70's there are suggestions that I might take retirement more seriously and stop going into the office most weekdays.  I would not want the package to atrophy if I step away from active development.

**Comment by nalimilan** [comment]
MixedModels would be welcome in JuliaStats as far as I'm concerned.

Regarding its addition to Stats.jl, the issue that I hard spotted at https://github.com/JuliaStats/Stats.jl/pull/4#issuecomment-389795494 is that it exports `bootstrap`, which is also exported by Bootstrap.jl. Is there any chance MixedModels could add a method to `Bootstrap.bootstrap` instead?

**Comment by nalimilan** [comment]
Everything is clear now AFAICT, so should we add MixedModels?

**Comment by dmbates** [comment]
@nalimilan Are you asking about adding MixedModels to StatsKit or transferring ownership to the JuliaStats group?

**Comment by mkborregaard** [comment]
I'd hope both

**Comment by dmbates** [comment]
Okay, I will make the transfer.  Will it be necessary to release a new version to get the entry in the package registry to point to the archive's new owner?

Also will those who currently have commit access to the repository (@palday) continue to do so?

**Comment by nalimilan** [comment]
I was only asking about adding MixedModels to StatsKit, but why not move it to JuliaStats too. These are totally independent operations, though.

You'll just have to make a PR against the registry to change the URL at https://github.com/JuliaRegistries/General/blob/master/M/MixedModels/Package.toml after moving the package. AFAIK, users with commit access will keep it.

**Comment by nalimilan** [comment]
@dmbates How is the transfer to JuliaStats going?

**Comment by dmbates** [comment]
Thanks for the reminder, @nalimilan .  I have now performed the transfer.
